README.md, custodial-wallet/api/get_supported_coins.mdx, custodial-wallet/api/transaction.mdx, custodial-wallet/introduction.mdx, introduction.mdx, mpc-wallet/api/auth_unbind_binding.mdx, mpc-wallet/api/mpc_list_tss_node.mdx, mpc-wallet/mpc-introduction.mdx, mpc-wallet/waas-reference/callback-signature.mdx, mpc-wallet/waas-reference/transaction-notification.mdx, smart-contract-wallet/coboargus.mdx, smart-contract-wallet/cobosafe.mdx, smart-contract-wallet/tools/overview.mdx, waas/authentication.mdx, waas/playground.mdx, waas/quickstart.mdx, waas/start-waas.mdx, waas/waas-reference/callback-signature.mdx, waas/waas-reference/transaction-notification.mdx
1.update environment name
2.update authentication content
3.Change Custody to Wallet
4.fix get_supported_coins content
=> Change Custody to Wallet

get-started/development/transaction-notification.mdx, overview/custodial-wallet.mdx, overview/introduction.mdx, overview/waas-introduction.mdx
1.update transaction-notification
2.Our WaaS is not RESTful
=> Our WaaS is not RESTful

api-references/mpc-wallet/mpc_get_supported_coins.mdx, get-started/sdks/waas/go.mdx, get-started/sdks/waas/java.mdx
=> update github url

api-references/mpc-wallet/mpc_get_supported_coins.mdx, api-references/mpc-wallet/mpc_get_supported_nft_collections.mdx, api-references/mpc-wallet/mpc_get_wallet_supported_coins.mdx, api-references/mpc-wallet/mpc_list_spendable.mdx, api-references/mpc-wallet/mpc_sign_message.mdx, api-references/mpc-wallet/mpc_sign_messages_by_cobo_ids.mdx, api-references/mpc-wallet/mpc_sign_messages_by_request_ids.mdx
1. add note for MPC and Web3 Wallets
=> add note for MPC and Web3 Wallets

get-started/overview/full-custody-quick-start.mdx, get-started/overview/mpc-lite-quick-start.mdx, get-started/overview/mpc-quick-start.mdx, get-started/sdks/waas/go.mdx, get-started/sdks/waas/java.mdx, get-started/sdks/waas/javascript.mdx, get-started/sdks/waas/php.mdx, get-started/sdks/waas/python.mdx
=> update mpc client example

api-references/custody-wallet/new_withdraw_request.mdx, api-references/custody-wallet/pending_transaction.mdx, api-references/custody-wallet/pending_transactions.mdx, api-references/custody-wallet/transaction.mdx, api-references/custody-wallet/transaction_by_txid.mdx, api-references/custody-wallet/transaction_history.mdx, api-references/custody-wallet/transactions_by_id.mdx, api-references/custody-wallet/transactions_by_request_ids.mdx, api-references/custody-wallet/transactions_by_time.mdx, api-references/custody-wallet/withdraw_info_by_request_id.mdx, api-references/development/changelog.mdx, api-references/mpc-wallet/mpc_create_transaction.mdx, api-references/mpc-wallet/mpc_list_transactions.mdx, api-references/mpc-wallet/mpc_transactions_by_cobo_ids.mdx, api-references/mpc-wallet/mpc_transactions_by_request_ids.mdx, api-references/mpc-wallet/mpc_transactions_by_tx_hash.mdx, overview/mpc-wallet/callback/callback-server-configuration.mdx
1. TSS callback RSA update to 4096
2. withdraw add remark param
=> withdraw add remark param

api-references/overview/authentication.mdx, get-started/overview/first-wallet-tutorial.mdx, get-started/overview/full-custody-quick-start.mdx, get-started/overview/mpc-lite-quick-start.mdx, get-started/overview/mpc-quick-start.mdx, get-started/sdks/waas/go.mdx, get-started/sdks/waas/java.mdx, get-started/sdks/waas/javascript.mdx, get-started/sdks/waas/php.mdx, get-started/sdks/waas/python.mdx, guides/howtos/configure-api-callback.mdx, guides/howtos/querying-deposit-transactions.mdx
Modify DEV_ENV parameters to align with the SDK code.
=> update env param:DEV_ENV

mint.json
=> change ga4 id

api-references/development/transaction-notification.mdx, api-references/development/withdrawal-confirmation.mdx
1.new transaction notification & withdrawal confirmation articles added
=> new transaction notification & withdrawal confirmation articles added

api-references/development/error-codes.mdx
=> add error codes

api-references/development/error-codes.mdx, api-references/mpc-wallet/mpc_create_transaction.mdx, guides/howtos/api-configuration-best-practices.mdx, guides/howtos/create-manage-deposit-addresses.mdx, mint.json, overview/mpc-wallet/mpc-introduction.mdx
=> add new guide

get-started/sdks/waas/python.mdx
=> update python sdk guide

api-references/custody-wallet/new_withdraw_request.mdx, api-references/custody-wallet/staking/staking_stake.mdx, api-references/custody-wallet/staking/staking_unstake.mdx, api-references/mpc-wallet/mpc_list_transactions.mdx, api-references/mpc-wallet/mpc_list_tss_node_requests.mdx, api-references/mpc-wallet/mpc_retry_double_check.mdx, api-references/mpc-wallet/mpc_transactions_by_cobo_ids.mdx, api-references/mpc-wallet/mpc_transactions_by_request_ids.mdx, api-references/mpc-wallet/mpc_transactions_by_tx_hash.mdx
=> update withdraw response

api-references/overview/authentication.mdx, guides/howtos/auto-token-sweeping-for-mpc-wallets.mdx
=> token sweep add codes

guides/howtos/auto-token-sweeping-for-mpc-wallets.mdx
=> add code blocks

_snippets/full_custodian_transaction_snippet.mdx, api-references/mpc-wallet/mpc_drop_transaction.mdx, get-started/sdks/waas/go.mdx, get-started/sdks/waas/java.mdx, get-started/sdks/waas/javascript.mdx, get-started/sdks/waas/php.mdx, get-started/sdks/waas/python.mdx, mint.json
=> update sdk guides

api-references/custody-wallet/coin_info.mdx, api-references/custody-wallet/new_address.mdx, api-references/custody-wallet/new_addresses.mdx, api-references/custody-wallet/new_withdraw_request.mdx, api-references/custody-wallet/staking/staking_stake.mdx, api-references/custody-wallet/staking/staking_unstake.mdx, api-references/custody-wallet/trading/trading_deposit.mdx, api-references/custody-wallet/trading/trading_transfer.mdx, api-references/custody-wallet/trading/trading_withdraw.mdx, api-references/mpc-wallet/auth_bind_addresses.mdx, api-references/mpc-wallet/auth_change_binding.mdx, api-references/mpc-wallet/auth_create_binding.mdx, api-references/mpc-wallet/auth_unbind_binding.mdx, api-references/mpc-wallet/mpc_create_transaction.mdx, api-references/mpc-wallet/mpc_drop_transaction.mdx, api-references/mpc-wallet/mpc_generate_addresses.mdx, api-references/mpc-wallet/mpc_retry_double_check.mdx, api-references/mpc-wallet/mpc_sign_message.mdx, api-references/mpc-wallet/mpc_speedup_transaction.mdx, api-references/mpc-wallet/mpc_update_address_description.mdx
Hi 👋 Mintlify engineer here
Mintlify issue is because the POST data is being sent as JSON instead of form data. The problem will be fixed tomorrow morning, but we need to make sure the pages are marked as `multipart/form-data` first
=> add `multipart/form-data` for POST requests

api-references/development/testing.mdx, api-references/mpc-wallet/mpc_sign_message.mdx, guides/howtos/rbf.mdx, mint.json
=> 1. add rbf guide

api-references/custody-wallet/coin_info.mdx, api-references/development/changelog.mdx
=> add new params to coin info

api-references/development/withdrawal-confirmation.mdx
edited 'withdrawal confirmation'
=> api-references/development/withdrawal-confirmation.mdx

api-references/development/transaction-notification.mdx, sdks-and-tools/sdks/waas/python.mdx
1.add mpc wallet callback content
=> add mpc wallet callback content

api-references/custody-wallet/new_addresses.mdx
1.update generate addresses content
=> update generate addresses content

api-references/custody-wallet/coin_info.mdx, api-references/development/address-encoding.mdx, api-references/development/testing.mdx, api-references/mpc-wallet/mpc_generate_addresses.mdx, api-references/mpc-wallet/mpc_list_addresses.mdx, api-references/mpc-wallet/mpc_update_address_description.mdx, mint.json
=> add address encodings

.fabistrano/sandbox/supervisor.json
=> upload supervisor.json

api-references/overview/authentication.mdx, faqs/api-key.mdx
=> update custody domain

mint.json
=> add babylon staking

README.md, mint.json, v2/api-references/dev_openapi.yaml, v2/api-references/overview/introduction.mdx, v2/api-references/wallets/list-enabled-chains.mdx, v2/api-references/wallets/list-enabled-tokens.mdx, v2/api-references/wallets/list-supported-chains.mdx, v2/api-references/wallets/list-supported-tokens.mdx, v2/cobo_waas2_openapi_spec/dev_openapi.yaml
=> update waas2 content

v2/api-references/dev_openapi.yaml, v2/cobo_waas2_openapi_spec/dev_openapi.yaml, v2/developer-tools/quickstart-python.mdx, v2/guides/overview/changelog.mdx, v2/guides/overview/cobo-auth.mdx
=> fix broken url

mint.json
=> fix babylon

v2/cobo_waas2_openapi_spec/dev_openapi.yaml
=> fix broken links

styles.css
=> add styles.css

mint.json
=> remove postman page

v2/guides/overview/changelog.mdx
=> update v2 changelog

mint.json
=> fix link bug

api_playground.js
=> add api_playground.js

v2/cobo_waas2_openapi_spec/dev_openapi.yaml
=> fix bad links

v1/api-references/mpc-wallet/mpc_estimate_fee.mdx, v1/api-references/mpc-wallet/mpc_get_approval_details.mdx, v1/api-references/mpc-wallet/mpc_get_supported_chains.mdx, v2/api-references/primebroker/bind-addresses-to-a-broker-user.mdx, v2/api-references/primebroker/change-guard-pubkey-binding.mdx, v2/api-references/primebroker/create-guard-pubkey-binding.mdx, v2/api-references/primebroker/delete-guard-pubkey-binding.mdx, v2/api-references/primebroker/query-a-guard-pubkey.mdx, v2/api-references/primebroker/query-approval-statement.mdx, v2/api-references/transactions/get-transaction-approval-details.mdx, v2/api-references/transactions/sign-and-broadcast-transaction.mdx, v2/api-references/transactions/sign-message.mdx, v2/api-references/travelrule/list-supported-countries.mdx, v2/api-references/travelrule/retrieve-transaction-limitations.mdx, v2/api-references/travelrule/submit-travel-rule-information-for-deposits.mdx, v2/api-references/travelrule/submit-travel-rule-information-for-withdrawals.mdx, v2/api-references/wallets--mpc-wallets/get-key-share-holder-information.mdx, v2/api-references/wallets--mpc-wallets/list-all-key-share-holders.mdx, v2/api-references/wallets/list-address-balances-by-token.mdx
=> update code samples
